name: Maven Package

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github

      - name: Build with Maven
        run: mvn --settings settings.xml clean install

      - name: Publish to GitHub Packages Apache Maven
        run: mvn --settings settings.xml deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}